identifier = "CHM:CHMTeam"
name = "Hard mode"
description = "VE Hard mode mod"
authors = ["View Author file"]
tags = ["Overhaul"]
dependencies = ["VoxelEras:DestinyHailstorm"]
game_versions = ["1.4"]
entry = "entry.rhai"
version = "0.0.1"
sync_mode = "Required"
provide_to_others = true
